<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Modules\GestionAcademica\Models\Teacher; 

class TeacherSeeder extends Seeder
{
    public function run()
    {
        $teachers = [
            [
                'first_name' => 'Carlos',
                'last_name' => 'Mendoza',
                'email' => 'carlos.mendoza@universidad.edu',
                'phone' => '+57 300 123 4567',
                'specialty' => 'Programación',
                'specialties' => json_encode(['Java', 'Python', 'Bases de Datos']),
                'curriculum' => 'Ingeniero de Sistemas con 10 años de experiencia en desarrollo de software. Especialista en Java y Python. Certificado en AWS y Scrum Master.',
                'years_experience' => 10,
                'academic_degree' => 'Maestría en Ingeniería de Software',
                'is_active' => true,
                'availability_notes' => 'Disponible en las mañanas de lunes a viernes. Prefiere grupos de máximo 30 estudiantes.',
            ],
            [
                'first_name' => 'Ana',
                'last_name' => 'García',
                'email' => 'ana.garcia@universidad.edu',
                'phone' => '+57 301 234 5678',
                'specialty' => 'Matemáticas',
                'specialties' => json_encode(['Cálculo', 'Álgebra', 'Estadística']),
                'curriculum' => 'Licenciada en Matemáticas con 8 años de experiencia en docencia universitaria. Investigadora en métodos cuantitativos.',
                'years_experience' => 8,
                'academic_degree' => 'Licenciatura en Matemáticas',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario de tarde. Experta en tutorías personalizadas.',
            ],
            [
                'first_name' => 'Luis',
                'last_name' => 'Fernández',
                'email' => 'luis.fernandez@universidad.edu',
                'phone' => '+57 302 345 6789',
                'specialty' => 'Bases de Datos',
                'specialties' => json_encode(['SQL', 'MongoDB', 'Oracle', 'PostgreSQL']),
                'curriculum' => 'Ingeniero de Sistemas especializado en bases de datos. 12 años de experiencia en diseño e implementación de sistemas de información.',
                'years_experience' => 12,
                'academic_degree' => 'Especialización en Bases de Datos',
                'is_active' => true,
                'availability_notes' => 'Disponible todo el día los martes y jueves. Consultor en proyectos de base de datos.',
            ],
            [
                'first_name' => 'María',
                'last_name' => 'López',
                'email' => 'maria.lopez@universidad.edu',
                'phone' => '+57 303 456 7890',
                'specialty' => 'Redes de Computadores',
                'specialties' => json_encode(['Cisco', 'Seguridad', 'Protocolos', 'Firewalls']),
                'curriculum' => 'Ingeniera de Telecomunicaciones con 9 años de experiencia en redes y seguridad. Certificada CCNA y CCNP.',
                'years_experience' => 9,
                'academic_degree' => 'Maestría en Telecomunicaciones',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario matutino. Coordinadora del laboratorio de redes.',
            ],
            [
                'first_name' => 'Javier',
                'last_name' => 'Ramírez',
                'email' => 'javier.ramirez@universidad.edu',
                'phone' => '+57 304 567 8901',
                'specialty' => 'Inteligencia Artificial',
                'specialties' => json_encode(['Machine Learning', 'Deep Learning', 'Python', 'TensorFlow']),
                'curriculum' => 'Doctor en Ciencias de la Computación. Especialista en IA y Machine Learning. Investigador principal en proyectos de visión por computadora.',
                'years_experience' => 15,
                'academic_degree' => 'Doctorado en Ciencias de la Computación',
                'is_active' => true,
                'availability_notes' => 'Disponible lunes, miércoles y viernes en la tarde. Director del grupo de investigación en IA.',
            ],
            [
                'first_name' => 'Elena',
                'last_name' => 'Martínez',
                'email' => 'elena.martinez@universidad.edu',
                'phone' => '+57 305 678 9012',
                'specialty' => 'Ingeniería de Software',
                'specialties' => json_encode(['Metodologías Ágiles', 'Patrones de Diseño', 'Testing', 'DevOps']),
                'curriculum' => 'Ingeniera de Software con 11 años de experiencia en desarrollo y gestión de proyectos. Certificada en Scrum y PMP.',
                'years_experience' => 11,
                'academic_degree' => 'Maestría en Gestión de Proyectos',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario flexible. Coordinadora de prácticas empresariales.',
            ],
            [
                'first_name' => 'Ricardo',
                'last_name' => 'Silva',
                'email' => 'ricardo.silva@universidad.edu',
                'phone' => '+57 306 789 0123',
                'specialty' => 'Sistemas Operativos',
                'specialties' => json_encode(['Linux', 'Windows Server', 'Virtualización', 'Contenedores']),
                'curriculum' => 'Ingeniero de Sistemas con 7 años de experiencia en administración de sistemas. Especialista en infraestructura cloud.',
                'years_experience' => 7,
                'academic_degree' => 'Ingeniería de Sistemas',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario de mañana. Responsable del laboratorio de sistemas operativos.',
            ],
            [
                'first_name' => 'Patricia',
                'last_name' => 'Castro',
                'email' => 'patricia.castro@universidad.edu',
                'phone' => '+57 307 890 1234',
                'specialty' => 'Estadística',
                'specialties' => json_encode(['Estadística Descriptiva', 'Probabilidad', 'R', 'Análisis de Datos']),
                'curriculum' => 'Licenciada en Estadística con 6 años de experiencia en análisis de datos. Investigadora en métodos estadísticos aplicados.',
                'years_experience' => 6,
                'academic_degree' => 'Licenciatura en Estadística',
                'is_active' => true,
                'availability_notes' => 'Disponible martes y jueves todo el día. Tutora de trabajos de grado.',
            ],
            [
                'first_name' => 'Fernando',
                'last_name' => 'Ortiz',
                'email' => 'fernando.ortiz@universidad.edu',
                'phone' => '+57 308 901 2345',
                'specialty' => 'Física',
                'specialties' => json_encode(['Física General', 'Mecánica', 'Termodinámica', 'Electromagnetismo']),
                'curriculum' => 'Licenciado en Física con 5 años de experiencia en docencia. Investigador en física aplicada a la computación.',
                'years_experience' => 5,
                'academic_degree' => 'Licenciatura en Física',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario de tarde. Coordinador del club de ciencias.',
            ],
            [
                'first_name' => 'Gabriela',
                'last_name' => 'Rojas',
                'email' => 'gabriela.rojas@universidad.edu',
                'phone' => '+57 309 012 3456',
                'specialty' => 'Química',
                'specialties' => json_encode(['Química General', 'Orgánica', 'Inorgánica', 'Bioquímica']),
                'curriculum' => 'Licenciada en Química con 4 años de experiencia en laboratorio y docencia. Especialista en química computacional.',
                'years_experience' => 4,
                'academic_degree' => 'Licenciatura en Química',
                'is_active' => true,
                'availability_notes' => 'Disponible lunes a viernes en la mañana. Responsable del laboratorio de química.',
            ],
            [
                'first_name' => 'Diego',
                'last_name' => 'Hernández',
                'email' => 'diego.hernandez@universidad.edu',
                'phone' => '+57 310 123 4567',
                'specialty' => 'Desarrollo Web',
                'specialties' => json_encode(['JavaScript', 'React', 'Node.js', 'APIs']),
                'curriculum' => 'Desarrollador Full Stack con 8 años de experiencia. Especialista en aplicaciones web escalables y modernas.',
                'years_experience' => 8,
                'academic_degree' => 'Ingeniería de Sistemas',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario flexible. Mentor en proyectos de desarrollo web.',
            ],
            [
                'first_name' => 'Sandra',
                'last_name' => 'Morales',
                'email' => 'sandra.morales@universidad.edu',
                'phone' => '+57 311 234 5678',
                'specialty' => 'Ciberseguridad',
                'specialties' => json_encode(['Ethical Hacking', 'Forensics', 'Pentesting', 'Security']),
                'curriculum' => 'Especialista en ciberseguridad con 9 años de experiencia. Certificada CEH y CISSP. Investigadora en seguridad ofensiva.',
                'years_experience' => 9,
                'academic_degree' => 'Maestría en Ciberseguridad',
                'is_active' => true,
                'availability_notes' => 'Disponible miércoles y viernes. Coordinadora del equipo de seguridad informática.',
            ],
            [
                'first_name' => 'Roberto',
                'last_name' => 'Díaz',
                'email' => 'roberto.diaz@universidad.edu',
                'phone' => '+57 312 345 6789',
                'specialty' => 'Arquitectura de Software',
                'specialties' => json_encode(['Microservicios', 'Cloud', 'Design Patterns', 'Scalability']),
                'curriculum' => 'Arquitecto de software con 14 años de experiencia. Especialista en diseño de sistemas empresariales escalables.',
                'years_experience' => 14,
                'academic_degree' => 'Doctorado en Arquitectura de Software',
                'is_active' => true,
                'availability_notes' => 'Disponible lunes y jueves. Consultor en arquitectura empresarial.',
            ],
            [
                'first_name' => 'Laura',
                'last_name' => 'Vargas',
                'email' => 'laura.vargas@universidad.edu',
                'phone' => '+57 313 456 7890',
                'specialty' => 'UX/UI Design',
                'specialties' => json_encode(['User Research', 'Prototyping', 'Figma', 'Design Systems']),
                'curriculum' => 'Diseñadora UX/UI con 6 años de experiencia. Especialista en investigación de usuarios y diseño centrado en el humano.',
                'years_experience' => 6,
                'academic_degree' => 'Maestría en Diseño de Interacción',
                'is_active' => true,
                'availability_notes' => 'Disponible en horario de mañana. Coordinadora del laboratorio de diseño.',
            ]
        ];

        foreach ($teachers as $teacher) {
            // USAR updateOrCreate PARA EVITAR DUPLICADOS
            Teacher::updateOrCreate(
                ['email' => $teacher['email']], // Buscar por email único
                $teacher // Datos para actualizar o crear
            );
        }
    }
}